export const hyperlaneMapping = {
  ethereum: [
    "BNB Smart Chain",
    "Polygon",
    "Avalanche",
    "Fantom",
    "Klaytn",
    "Celo",
    "Moonbeam",
    "Arbitrum One",
    "OP Mainnet",
  ],
  "BNB Smart Chain": [
    "Ethereum",
    "Polygon",
    "Avalanche",
    "Fantom",
    "Klaytn",
    "Celo",
    "Moonbeam",
    "Arbitrum One",
    "OP Mainnet",
  ],

  Polygon: [
    "Ethereum",
    "BNB Smart Chain",
    "Avalanche",
    "Fantom",
    "Klaytn",
    "Celo",
    "Moonbeam",
    "Arbitrum One",
    "OP Mainnet",
  ],

  Avalanche: [
    "Ethereum",
    "BNB Smart Chain",
    "Polygon",
    "Fantom",
    "Klaytn",
    "Celo",
    "Moonbeam",
    "Arbitrum One",
    "OP Mainnet",
  ],

  Fantom: [
    "Ethereum",
    "BNB Smart Chain",
    "Polygon",
    "Avalanche",
    "Klaytn",
    "Celo",
    "Moonbeam",
    "Arbitrum One",
    "OP Mainnet",
  ],

  Klaytn: [
    "Ethereum",
    "BNB Smart Chain",
    "Polygon",
    "Avalanche",
    "Fantom",
    "Celo",
    "Moonbeam",
    "Arbitrum One",
    "OP Mainnet",
  ],

  Celo: [
    "Ethereum",
    "BNB Smart Chain",
    "Polygon",
    "Avalanche",
    "Fantom",
    "Klaytn",
    "Moonbeam",
    "Arbitrum One",
    "OP Mainnet",
  ],

  Moonbeam: [
    "Ethereum",
    "BNB Smart Chain",
    "Polygon",
    "Avalanche",
    "Fantom",
    "Klaytn",
    "Celo",
    "Arbitrum One",
    "OP Mainnet",
  ],

  "Arbitrum One": [
    "Ethereum",
    "BNB Smart Chain",
    "Polygon",
    "Avalanche",
    "Fantom",
    "Klaytn",
    "Celo",
    "Moonbeam",
    "OP Mainnet",
  ],

  "OP Mainnet": [
    "Ethereum",
    "BNB Smart Chain",
    "Polygon",
    "Avalanche",
    "Fantom",
    "Klaytn",
    "Celo",
    "Moonbeam",
    "Arbitrum One",
  ],

  Sepolia: [
    "Goerli",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
    "Arbitrum",
    "Optimism",
  ],

  "Polygon Mumbai": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    // "Mantle Testnet",
    "Metis Goerli",
  ],

  "Binance Smart Chain Testnet": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
};
