export const layerZeroMapping = {
  "Polygon zkEVM Testnet": [
    "Goerli",
    // "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  Sepolia: [
    "Goerli",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
    "Arbitrum",
    "Optimism",
  ],
  Goerli: [
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    "Mantle Testnet",
    "Metis Goerli",
  ],
  "Arbitrum Goerli": [
    "Goerli",
    "Sepolia",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  "Optimism Goerli": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  "Base Goerli": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  "Linea Goerli Testnet": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  "Binance Smart Chain Testnet": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  "Polygon Mumbai": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
  "Mantle Testnet": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    "Metis Goerli",
  ],
  "Metis Goerli": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    "Mantle Testnet",
  ],

  // MAINNET MAPPINGS

  Blast: [
    "Arbitrum One",
    "Avalanche",
    "Base",
    "BNB Smart Chain",
    "Celo",
    "Fantom",
    "Gnosis",
    "Linea",
    "Manta Pacific",
    "opBNB",
    "OP Mainnet",
    "Polygon",
    "Polygon zkEVM",
    "Scroll",
    "zkSync Era",
    "Zora",
  ],

  Base: [
    "Arbitrum One",
    "Avalanche",
    "Blast",
    "BNB Smart Chain",
    "Celo",
    "Fantom",
    "Gnosis",
    "Linea",
    "Manta Pacific",
    "opBNB",
    "OP Mainnet",
    "Polygon",
    "Polygon zkEVM",
    "Scroll",
    "zkSync Era",
    "Zora",
  ],

  Gnosis: [
    "Arbitrum One",
    "Avalanche",
    "Blast",
    "Base",
    "BNB Smart Chain",
    "Celo",
    "Fantom",
    "Linea",
    "Manta Pacific",
    "opBNB",
    "OP Mainnet",
    "Polygon",
    "Polygon zkEVM",
    "Scroll",
    "zkSync Era",
    "Zora",
  ],
  Linea: [
    "Arbitrum One",
    "Avalanche",
    "Blast",
    "Base",
    "BNB Smart Chain",
    "Celo",
    "Fantom",
    "Gnosis",
    "Manta Pacific",
    "opBNB",
    "OP Mainnet",
    "Polygon",
    "Polygon zkEVM",
    "Scroll",
    "zkSync Era",
    "Zora",
  ],
  "Arbitrum One": [
    "Base",
    "Blast",
    "Linea",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Metis",
    "Mantle",
    "Core Dao",
    "Gnosis",
    "Avalanche",
    "Canto",
    "Fantom",
    "Harmony One",
    "Celo",
    "Kava EVM",
    "Sepolia",
    "DFK",
    "Moonbeam",
    "Moonriver",
    "Fuse",
    "OKT (OKX)",
    "Tenet",
    "Meter",
    "Loot",
    "Beam",
    "Zora",
    "opBNB",
    "Astar",
    "Conflux",
    "Telos",
    "Aurora",
    "Tomo",
    "Scroll",
    "Manta Pacific",
    "PGN",
  ],
  "Arbitrum Nova": [
    "Base",
    "Arbitrum One",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Metis",
    "Avalanche",
    "Canto",
    "Fantom",
    "Kava EVM",
    "Moonbeam",
    "Tenet",
    "Meter",
  ],
  "OP Mainnet": [
    "Arbitrum One",
    "Avalanche",
    "Blast",
    "Base",
    "BNB Smart Chain",
    "Celo",
    "Fantom",
    "Gnosis",
    "Linea",
    "Manta Pacific",
    "opBNB",
    "Polygon",
    "Polygon zkEVM",
    "Scroll",
    "zkSync Era",
    "Zora",
  ],
  opBNB: [
    "Arbitrum One",
    "Avalanche",
    "Blast",
    "Base",
    "BNB Smart Chain",
    "Celo",
    "Fantom",
    "Gnosis",
    "Linea",
    "Manta Pacific",
    "OP Mainnet",
    "Polygon",
    "Polygon zkEVM",
    "Scroll",
    "zkSync Era",
    "Zora",
  ],
  Scroll: [
    "Arbitrum One",
    "Avalanche",
    "Blast",
    "Base",
    "BNB Smart Chain",
    "Celo",
    "Fantom",
    "Gnosis",
    "Linea",
    "Manta Pacific",
    "opBNB",
    "OP Mainnet",
    "Polygon",
    "Polygon zkEVM",
    "zkSync Era",
    "Zora",
  ],
  "zkSync Era": [
    "Arbitrum One",
    "Avalanche",
    "Blast",
    "Base",
    "BNB Smart Chain",
    "Celo",
    "Fantom",
    "Gnosis",
    "Linea",
    "Manta Pacific",
    "opBNB",
    "OP Mainnet",
    "Polygon",
    "Polygon zkEVM",
    "Scroll",
    "Zora",
  ],
  Zora: [
    "Arbitrum One",
    "Avalanche",
    "Blast",
    "Base",
    "BNB Smart Chain",
    "Celo",
    "Fantom",
    "Gnosis",
    "Linea",
    "Manta Pacific",
    "opBNB",
    "OP Mainnet",
    "Polygon",
    "Polygon zkEVM",
    "Scroll",
    "zkSync Era",
  ],
  "BNB Smart Chain": [
    "Arbitrum One",
    "Avalanche",
    "Blast",
    "Base",
    "Celo",
    "Fantom",
    "Gnosis",
    "Linea",
    "Manta Pacific",
    "opBNB",
    "OP Mainnet",
    "Polygon",
    "Polygon zkEVM",
    "Scroll",
    "zkSync Era",
    "Zora",
  ],
  Polygon: [
    "Arbitrum One",
    "Avalanche",
    "Blast",
    "Base",
    "BNB Smart Chain",
    "Celo",
    "Fantom",
    "Gnosis",
    "Linea",
    "Manta Pacific",
    "opBNB",
    "OP Mainnet",
    "Polygon zkEVM",
    "Scroll",
    "zkSync Era",
    "Zora",
  ],
  "Polygon zkEVM": [
    "Arbitrum One",
    "Avalanche",
    "Blast",
    "Base",
    "BNB Smart Chain",
    "Celo",
    "Fantom",
    "Gnosis",
    "Linea",
    "Manta Pacific",
    "opBNB",
    "OP Mainnet",
    "Polygon",
    "Scroll",
    "zkSync Era",
    "Zora",
  ],
  Mantle: [
    "Base",
    "Linea",
    "Arbitrum One",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Metis",
    "Avalanche",
    "Fantom",
    "Moonbeam",
    "Telos",
    "Scroll",
  ],
  Metis: [
    "Base",
    "Linea",
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Mantle",
    "Gnosis",
    "Avalanche",
    "Canto",
    "Fantom",
    "Kava EVM",
    "Moonriver",
    "Fuse",
    "Klaytn",
    "Tenet",
    "Meter",
  ],
  "Core Dao": [
    "Arbitrum One",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Avalanche",
  ],
  Avalanche: [
    "Arbitrum One",
    "Blast",
    "Base",
    "BNB Smart Chain",
    "Celo",
    "Fantom",
    "Gnosis",
    "Linea",
    "Manta Pacific",
    "opBNB",
    "OP Mainnet",
    "Polygon",
    "Polygon zkEVM",
    "Scroll",
    "zkSync Era",
    "Zora",
  ],
  Fantom: [
    "Arbitrum One",
    "Avalanche",
    "Blast",
    "Base",
    "BNB Smart Chain",
    "Celo",
    "Gnosis",
    "Linea",
    "Manta Pacific",
    "opBNB",
    "OP Mainnet",
    "Polygon",
    "Polygon zkEVM",
    "Scroll",
    "zkSync Era",
    "Zora",
  ],
  Celo: [
    "Arbitrum One",
    "Avalanche",
    "Blast",
    "Base",
    "BNB Smart Chain",
    "Fantom",
    "Gnosis",
    "Linea",
    "Manta Pacific",
    "opBNB",
    "OP Mainnet",
    "Polygon",
    "Polygon zkEVM",
    "Scroll",
    "zkSync Era",
    "Zora",
  ],
  Moonbeam: [
    "Base",
    "Linea",
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Mantle",
    "Avalanche",
    "Fantom",
    "Harmony One",
    "Celo",
    "DFK",
    "Scroll",
  ],
  Moonriver: [
    "Base",
    "Linea",
    "Arbitrum One",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Metis",
    "Avalanche",
    "Fantom",
    "Kava EVM",
    "Scroll",
  ],
  Canto: [
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Metis",
    "Avalanche",
    "Fantom",
    "Tenet",
    "Meter",
  ],
  "Harmony One": [
    "Arbitrum One",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Avalanche",
    "Fantom",
    "DFK",
    "Moonbeam",
  ],
  Fuse: [
    "Arbitrum One",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Metis",
    "Gnosis",
    "Avalanche",
    "Celo",
    "Klaytn",
  ],
  Meter: [
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Metis",
    "Avalanche",
    "Canto",
    "Fantom",
    "Tenet",
  ],
  Aurora: [
    "Arbitrum One",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Avalanche",
  ],
  Klaytn: ["BNB Smart Chain", "Metis", "Gnosis", "Avalanche", "DFK", "Fuse"],
  Astar: [
    "Base",
    "Linea",
    "Arbitrum One",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Avalanche",
  ],
  Tenet: [
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Metis",
    "Avalanche",
    "Canto",
    "Fantom",
    "Meter",
  ],
  "Manta Pacific": [
    "Arbitrum One",
    "Avalanche",
    "Blast",
    "Base",
    "BNB Smart Chain",
    "Celo",
    "Fantom",
    "Gnosis",
    "Linea",
    "opBNB",
    "OP Mainnet",
    "Polygon",
    "Polygon zkEVM",
    "Scroll",
    "zkSync Era",
    "Zora",
  ],
  PGN: [
    "Arbitrum One",
    "OP Mainnet",
    "BNB Smart Chain",
    "Polygon",
    "Avalanche",
    "Manta Pacific",
  ],
  "Kava EVM": [
    "Base",
    "Linea",
    "Arbitrum One",
    "Arbitrum Nova",
    "OP Mainnet",
    "zkSync Era",
    "BNB Smart Chain",
    "Polygon",
    "Polygon zkEVM",
    "Metis",
    "Avalanche",
    "Fantom",
    "Moonriver",
  ],
};
