const chains = [
  "bsc",
  "arbitrum",
  "optimism",
  "gnosis",
  "base",
  "scroll",
  "polygon-zkEVM",
  "celo",
  "avalanche",
  "polygon",
  "moonbeam",
];

export const hyperlaneMapping = {
  ethereum: [
    "BNB Smart Chain",
    "Polygon",
    "Avalanche",
    "Celo",
    "Moonbeam",
    "Arbitrum One",
    "OP Mainnet",
    "Scroll",
    "Gnosis",
    "Base",
    "Polygon zkEVM",
  ],

  Base: [
    "Ethereum",
    "Polygon",
    "BNB Smart Chain",
    "Avalanche",
    "Celo",
    "Moonbeam",
    "Arbitrum One",
    "OP Mainnet",
    "Scroll",
    "Gnosis",
    "Polygon zkEVM",
  ],
  Gnosis: [
    "Ethereum",
    "Polygon",
    "BNB Smart Chain",
    "Avalanche",
    "Celo",
    "Moonbeam",
    "Arbitrum One",
    "OP Mainnet",
    "Scroll",
    "Base",
    "Polygon zkEVM",
  ],

  Scroll: [
    "Ethereum",
    "Polygon",
    "BNB Smart Chain",
    "Avalanche",
    "Celo",
    "Moonbeam",
    "Arbitrum One",
    "OP Mainnet",
    "Gnosis",
    "Base",
    "Polygon zkEVM",
  ],

  "Polygon zkEVM": [
    "Ethereum",
    "Polygon",
    "BNB Smart Chain",
    "Avalanche",
    "Celo",
    "Moonbeam",
    "Arbitrum One",
    "OP Mainnet",
    "Scroll",
    "Gnosis",
    "Base",
  ],

  "BNB Smart Chain": [
    "Ethereum",
    "Polygon",
    "Avalanche",
    "Celo",
    "Moonbeam",
    "Arbitrum One",
    "OP Mainnet",
    "Scroll",
    "Gnosis",
    "Base",
    "Polygon zkEVM",
  ],

  Polygon: [
    "Ethereum",
    "BNB Smart Chain",
    "Avalanche",
    "Celo",
    "Moonbeam",
    "Arbitrum One",
    "OP Mainnet",
    "Scroll",
    "Gnosis",
    "Base",
    "Polygon zkEVM",
  ],

  Avalanche: [
    "Ethereum",
    "Polygon",
    "BNB Smart Chain",
    "Celo",
    "Moonbeam",
    "Arbitrum One",
    "OP Mainnet",
    "Scroll",
    "Gnosis",
    "Base",
    "Polygon zkEVM",
  ],

  Celo: [
    "Ethereum",
    "Polygon",
    "BNB Smart Chain",
    "Avalanche",
    "Moonbeam",
    "Arbitrum One",
    "OP Mainnet",
    "Scroll",
    "Gnosis",
    "Base",
    "Polygon zkEVM",
  ],

  Moonbeam: [
    "Ethereum",
    "Polygon",
    "BNB Smart Chain",
    "Avalanche",
    "Celo",
    "Arbitrum One",
    "OP Mainnet",
    "Scroll",
    "Gnosis",
    "Base",
    "Polygon zkEVM",
  ],

  "Arbitrum One": [
    "Ethereum",
    "Polygon",
    "BNB Smart Chain",
    "Avalanche",
    "Celo",
    "Moonbeam",
    "OP Mainnet",
    "Scroll",
    "Gnosis",
    "Base",
    "Polygon zkEVM",
  ],

  "OP Mainnet": [
    "Ethereum",
    "Polygon",
    "BNB Smart Chain",
    "Avalanche",
    "Celo",
    "Moonbeam",
    "Arbitrum One",
    "Scroll",
    "Gnosis",
    "Base",
    "Polygon zkEVM",
  ],

  Sepolia: [
    "Goerli",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
    "Arbitrum",
    "Optimism",
  ],

  "Polygon Mumbai": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    "Binance Smart Chain Testnet",
    // "Polygon zkEVM Testnet",
    // "Mantle Testnet",
    "Metis Goerli",
  ],

  "Binance Smart Chain Testnet": [
    "Goerli",
    "Sepolia",
    "Arbitrum Goerli",
    "Optimism Goerli",
    "Base Goerli",
    "Linea Goerli Testnet",
    // "Polygon zkEVM Testnet",
    "Polygon Mumbai",
    // "Mantle Testnet",
    "Metis Goerli",
  ],
};
